apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portscanner-ds
  namespace: portscanner
spec:
  selector:
    matchLabels:
      app: portscanner
      k8s-app: portscanner
  template:
    metadata:
      labels:
        app: portscanner
        k8s-app: portscanner
      #annotations:
      #  iam.amazonaws.com/role: logging-sa
    spec:
      #tolerations: 
      #- key: node-role.kubernetes.io/master
      #  effect: NoSchedule
      #serviceAccount: logging-sa
      #serviceAccountName: logging-sa
      hostNetwork: true
      volumes:
        - name: fluentdconf
          configMap:
            name: fluentd-config
        - name: app-logs
          emptyDir: {}
      imagePullSecrets:
      - name: regcred 
      containers:
        - name: portscanner
          image: fgg89/nodeport-scanner:latest
          #command: ['sh', '-c']
          args:
          - 5
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /var/log/portscanner
            name: app-logs
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
              cpu: 400m
              memory: 1Gi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
