apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portscanner-ds
  namespace: portscanner
  labels:
    k8s-app: portscanner
spec:
  selector:
    matchLabels:
      name: portscanner
  template:
    metadata:
      labels:
        name: portscanner
      annotations:
        iam.amazonaws.com/role: logging-sa
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      imagePullSecrets:
      - name: regcred 
      hostNetwork: true
      serviceAccount: logging-sa
      serviceAccountName: logging-sa
      volumes:
      - name: fluentdconf
        configMap:
          name: fluentd-config
      - name: app-logs
        emptyDir: {}
      containers:
      - name: portscanner
        image: fgg89/nodeport-scanner:latest
        args: ["-i", "30"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/portscanner
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.9.3-debian-cloudwatch-1.0
        env:
        - name: REGION
          value: us-east-1
        - name: AWS_REGION
          value: us-east-1
        - name: CLUSTER_NAME
          value: fgonzalez-eks
        - name: CI_VERSION
          value: "k8s/1.0.1"
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentdconf
          mountPath: /fluentd/etc
        - name: app-logs
          mountPath: /var/log/portscanner
